before_script:
  - apt-get -q update
  - mount -o remount,rw /dev
  - env DEBIAN_FRONTEND=noninteractive apt-get -q -y install --no-install-recommends aspcud apt-cudf
  - env DEBIAN_FRONTEND=noninteractive apt-get -q -y --solver aspcud -o APT::Solver::Strict-Pinning=0 -o Debug::pkgProblemResolver=yes build-dep .

.test_template: &test
  script:
    - py.test-3 -vv -l -r a

unstable:
  <<: *test
  image: debian:unstable

testing:
  <<: *test
  image: debian:testing
  # in testing the build-dependencies are not installable.
  # keep trying, but ignore the failures
  allow_failure: true

stable-bpo:
  <<: *test
  image: debian:stable-backports

ubuntu-devel:
  <<: *test
  image: ubuntu:devel
